### ISSUE TITLE
Plugins not showing for Slack 3.3.8 on Linux

### ISSUE THREAD

**Issue by JavaOfDoom** [glajchs/slack-customizations#12]
I came across your repo and I was super excited to try it out, but I just can't get the plugins to to show. I've gone through all the issue suggestions from the past and haven't been able to get it to work. I'm probably missing something simple. Let me know what other information you need from me.
Thanks

**Comment by jamesdwilson** [comment]
Does `~/.slack` exist as a symlink pointing to `<project>/.slack`?

That was my problem. Also make sure you have the latest copy of this project.
