### ISSUE TITLE
Question - Nick Autocompletion

### ISSUE THREAD

**Issue by lenisko** [glajchs/slack-customizations#2]
Hi there!

I didn't really looked into code hence the question.
Is it possible to change/fix the way nick auto-completion is working in Slack?
As we know Slack borked it.

**Comment by glajchs** [comment]
Hi lenisko!

Actually this is the first I've heard about the issue, but if it is still an issue I'd be happy to try and fix it here in the plugins.  What is broken about it?  Do you know of any existing articles or discussions about the breakage?  When I try to auto complete nicks in my company's workspace it's working for me, but I haven't dug in too deep yet.

**Comment by glajchs** [comment]
Hey I haven't heard back from you yet, and some googling hasn't found any obvious issues with how slack's nick auto-completion is working, so I'm going to close this for now.  Feel free to re-open if you get any more information.
